[build]
  command = "yarn export"
  publish = "astro/dist/"

[[plugins]]
  package = "@resoc/netlify-plugin-social-image"
  [plugins.inputs]
    templates_dir = "resoc"
    open_graph_base_path = "/og-images"
    slug_to_image_data_function = "resoc/slug-to-image-data.js"