name: checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run prettier action
        uses: arnorhs/prettier-check@v1.0.9
        with:
          main-branch: master

  checks:
    name: CI checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - id: cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/.turbo
            **/dist
          key: global-cache-v3-${{ hashFiles('**/pnpm-*') }}
      - name: Install dependencies
        run: pnpm i
      - name: Turbo build
        run: pnpm turbo build
      - name: Turbo typecheck
        run: pnpm turbo typecheck
      - name: Turbo test
        run: pnpm turbo test
      - name: Turbo export
        run: pnpm turbo export

  checks-result:
    name: Checks OK
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs:
      - prettier
      - checks
    steps:
      - name: All deployed
        run: echo "All good"
