name: checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  checks:
    name: CI checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - id: cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/.turbo
            **/dist
          key: global-cache-v3
      - name: Install dependencies
        run: pnpm i
      - name: Prettier format check
        run: pnpm prettier --check .
      - name: Turbo typecheck
        run: pnpm turbo typecheck
      - name: Turbo test
        run: pnpm turbo test
      - name: Turbo build
        run: pnpm turbo build
