name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - id: cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/.turbo
            **/dist
          key: global-cache-v3
      - name: Install dependencies
        run: pnpm i
      - name: Turbo export
        run: pnpm turbo export
      - name: Deploy post images worker
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: 'pkg/post-images-worker'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy website
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: 'pkg/astro'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
